# ============================================
# LOG FILE DETECTIVE - Finds hackers in server records!
# ============================================

from collections import Counter  # Fancy counting tool
import re                        # Pattern finder

def create_sample_log():
    """
    Creates a fake server log file so you can practice without needing a real server!
    """
    log_content = """2026-05-31 08:15:23 - User admin logged in successfully from 192.168.1.5
2026-05-31 08:20:45 - User john logged in successfully from 192.168.1.10
2026-05-31 08:22:01 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:22:15 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:22:30 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:22:45 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:23:01 - FAILED login attempt for user 'root' from 10.0.0.99
2026-05-31 08:23:15 - FAILED login attempt for user 'root' from 10.0.0.99
2026-05-31 08:30:00 - User sarah logged in successfully from 192.168.1.20
2026-05-31 08:45:12 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:45:25 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:45:40 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:46:00 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 08:46:15 - FAILED login attempt for user 'admin' from 10.0.0.99
2026-05-31 09:00:00 - User mike logged in successfully from 192.168.1.15
2026-05-31 09:15:30 - User jane logged in successfully from 192.168.1.25
2026-05-31 09:20:01 - FAILED login attempt for user 'admin' from 172.16.0.50
2026-05-31 09:20:10 - FAILED login attempt for user 'admin' from 172.16.0.50
2026-05-31 09:20:20 - FAILED login attempt for user 'admin' from 172.16.0.50
2026-05-31 10:00:00 - User bob logged in successfully from 192.168.1.30
"""
    
    # Save the fake log to a file
    with open("server_log.txt", "w") as file:
        file.write(log_content)
    
    print("📄 Created 'server_log.txt' with sample hacker activity!")
    return log_content


def analyze_log(filename):
    """
    Reads the log file and finds suspicious activity!
    """
    print(f"\n🔍 ANALYZING: {filename}")
    print("=" * 60)
    
    # Read the file
    with open(filename, "r") as file:
        lines = file.readlines()
    
    # Lists to store what we find
    failed_attempts = []      # All failed logins
    successful_logins = []    # All successful logins
    suspicious_ips = []       # IPs that look suspicious
    
    # Go through each line like a detective!
    for line in lines:
        line = line.strip()  # Remove extra spaces
        
        if "FAILED" in line:
            # Extract IP address (4 numbers with dots, like 192.168.1.1)
            ip_match = re.search(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', line)
            if ip_match:
                ip = ip_match.group()
                failed_attempts.append(ip)
                
        elif "successfully" in line:
            ip_match = re.search(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', line)
            if ip_match:
                successful_logins.append(ip_match.group())
    
    # Count failed attempts per IP (like counting how many times someone knocked!)
    ip_counter = Counter(failed_attempts)
    
    # Find suspicious IPs (3+ failed attempts = probably a hacker!)
    print("🚨 SUSPICIOUS ACTIVITY DETECTED:")
    print("-" * 40)
    
    found_hackers = False
    for ip, count in ip_counter.most_common():
        if count >= 3:
            found_hackers = True
            print(f"   ⚠️  IP {ip}: {count} failed attempts!")
            print(f"      → Likely BRUTE-FORCE ATTACK (guessing passwords)")
            suspicious_ips.append(ip)
    
    if not found_hackers:
        print("   ✅ No suspicious activity found!")
    
    # Summary statistics
    print("\n📊 SECURITY REPORT SUMMARY:")
    print("-" * 40)
    print(f"   Total lines checked:     {len(lines)}")
    print(f"   Successful logins:       {len(successful_logins)}")
    print(f"   Failed attempts:         {len(failed_attempts)}")
    print(f"   Unique suspicious IPs:   {len(suspicious_ips)}")
    
    # Show all failed attempts breakdown
    print("\n📋 ALL FAILED ATTEMPTS BY IP:")
    print("-" * 40)
    for ip, count in ip_counter.most_common():
        status = "🚨 SUSPICIOUS" if count >= 3 else "⚠️  Warning"
        print(f"   {ip}: {count} attempts {status}")
    
    # Generate alert file
    if suspicious_ips:
        with open("security_alert.txt", "w") as alert:
            alert.write("🚨 SECURITY ALERT - Generated by Log Analyzer\n")
            alert.write("=" * 50 + "\n\n")
            alert.write("Suspicious IPs detected:\n")
            for ip in suspicious_ips:
                alert.write(f"   - {ip}: {ip_counter[ip]} failed attempts\n")
            alert.write("\nRecommended action: Block these IPs in firewall!\n")
        
        print("\n📝 Saved detailed alert to 'security_alert.txt'")


# ============================================
# MAIN PROGRAM
# ============================================

if __name__ == "__main__":
    print("🕵️  WELCOME TO LOG FILE DETECTIVE 🕵️")
    print("This tool finds hackers trying to break into servers!")
    
    # Create fake data to practice with
    create_sample_log()
    
    # Analyze it!
    analyze_log("server_log.txt")
    
    print("\n" + "=" * 60)
    print("🎓 WHAT YOU LEARNED:")
    print("   • Hackers try many passwords quickly (brute-force)")
    print("   • We can detect them by counting failed attempts")
    print("   • Real security teams use tools like this daily!")
    print("=" * 60)
